### ISSUE TITLE
META: Add vertical tab summary text to many settings

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#424]
Vertical tabs normally have summary text that displays the current value of the form elements in the tab. Some Ubercart settings pages don't have summary text (or it is only partial). Usability would be enhanced if they did, including:

- [x] admin/store/settings/store https://github.com/backdrop-contrib/ubercart/issues/462
- [x] admin/store/settings/cart https://github.com/backdrop-contrib/ubercart/issues/464
- [x] admin/store/settings/checkout https://github.com/backdrop-contrib/ubercart/issues/465

It may be impractical to show the values of all fields in the summary text, due to considerations of keeping the summary text short, but it would still be nice to show more than is currently shown.
